/**
 * The access-control checks that were previously only ever run by a human with
 * a browser open, and were therefore only true on the day someone looked.
 *
 * Three claims, each of which the README makes and none of which any unit test
 * can reach — they are properties of the whole stack answering a real HTTP
 * request, and the unit suite deliberately runs without a database:
 *
 *   1. A squad leader's roster is their squad and nothing else — not the
 *      sibling squad, not the parent platoon.
 *   2. A record they may not see is a 404 through BOTH the page and the API.
 *   3. A quartermaster never receives a whole service number, in any field of
 *      any response, however the record got into it.
 */

import { expect, test, type Page } from "@playwright/test";
import { PrismaPg } from "@prisma/adapter-pg";
/**
 * The lockdown in eslint.config.mjs keeps APPLICATION code away from an
 * unscoped client. This file is not application code: it has to read the
 * database from OUTSIDE the scoping layer to obtain an id the viewer under
 * test is not allowed to have — which is exactly what it then proves they
 * cannot use. Everything the app itself does still goes through a repository.
 */
// eslint-disable-next-line no-restricted-imports
import { PrismaClient } from "@prisma/client";

import { DEMO_PASSWORD } from "../lib/demo-users";
import type { EquipmentDTO } from "../lib/dto/equipment";
import { loadEnv } from "../lib/load-env";

const SQUAD_LEADER = "sgt.calder@example.mil";
const QUARTERMASTER = "cw2.petrov@example.mil";

const OWN_SQUAD = "2-14 IN / A / 1PLT / 1SQD";
const SIBLING_SQUAD = "2-14 IN / A / 1PLT / 2SQD";

/** Seeded squad strength. Asserted, not derived, so a seed change is visible here. */
const SQUAD_SIZE = 9;

/**
 * Personnel ids are cuids regenerated by every reseed, so they are looked up
 * rather than pinned. A hardcoded one would rot into a 404 for the wrong
 * reason — and a 404 for the wrong reason is exactly the failure this file
 * exists to catch, dressed as a pass.
 */
let siblingSquadId: string;
let ownSquadId: string;

test.beforeAll(async () => {
  loadEnv();

  const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error(
      "No DIRECT_URL or DATABASE_URL. Copy .env.example to .env.local and run `npm run db:up`.",
    );
  }

  const prisma = new PrismaClient({
    // Two connections, not the pg default of ten: PGlite is started with
    // --max-connections=10 and the dev server under test needs most of them.
    adapter: new PrismaPg({ connectionString, max: 2 }),
    log: ["warn", "error"],
  });

  try {
    const [sibling, own] = await Promise.all([
      prisma.personnel.findFirst({
        where: { unit: { designation: SIBLING_SQUAD }, deletedAt: null },
        orderBy: { serviceId: "asc" },
        select: { id: true },
      }),
      prisma.personnel.findFirst({
        where: { unit: { designation: OWN_SQUAD }, deletedAt: null },
        orderBy: { serviceId: "asc" },
        select: { id: true },
      }),
    ]);

    if (!sibling || !own) {
      throw new Error(
        `Squads ${OWN_SQUAD} and ${SIBLING_SQUAD} are not both populated. Run \`npm run db:seed\`.`,
      );
    }

    siblingSquadId = sibling.id;
    ownSquadId = own.id;
  } finally {
    await prisma.$disconnect();
  }
});

async function signIn(page: Page, email: string): Promise<void> {
  await page.goto("/login");
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill(DEMO_PASSWORD);
  await page.getByRole("button", { name: "Sign in" }).click();
  await page.waitForURL("**/personnel");
}

test("a squad leader's roster is their own squad and nothing else", async ({
  page,
}) => {
  await signIn(page, SQUAD_LEADER);

  await expect(
    page.getByText(`${SQUAD_SIZE} records in scope`),
  ).toBeVisible();

  // The table is fetched client-side from /api/personnel, so the count settles
  // a beat after the server-rendered rollup above it. Both come through the
  // same Scope; asserting them separately is what would catch them disagreeing.
  const rows = page.locator("tbody tr");
  await expect(rows).toHaveCount(SQUAD_SIZE);

  // The count alone would be satisfied by any other nine-person squad — every
  // squad in this brigade is nine. Asserting the designation on every row is
  // what pins the scope to theirs rather than merely to something the right
  // size.
  await expect(page.locator("tbody tr", { hasText: OWN_SQUAD })).toHaveCount(
    SQUAD_SIZE,
  );
  await expect(
    page.locator("tbody tr", { hasText: SIBLING_SQUAD }),
  ).toHaveCount(0);
});

test("a sibling squad's soldier is 404, not 403, from both the page and the API", async ({
  page,
}) => {
  await signIn(page, SQUAD_LEADER);

  /**
   * 404 and not 403 is the whole assertion.
   *
   * 403 would mean "this record exists and you may not have it", which hands
   * an attacker a membership oracle: walk ids, keep the 403s, and you have
   * enumerated the roster of a unit you were never allowed to see. 404 says
   * only "no such record for you", which is indistinguishable from a record
   * that never existed at all.
   */
  const pageResponse = await page.goto(`/personnel/${siblingSquadId}`);
  expect(pageResponse?.status()).toBe(404);

  const apiResponse = await page.request.get(`/api/personnel/${siblingSquadId}`);
  expect(apiResponse.status()).toBe(404);

  /**
   * The control, without which both assertions above pass for a stale id, a
   * typo, or a route that 404s for everyone. Their own squad must answer 200
   * through exactly the same two doors.
   */
  const ownPageResponse = await page.goto(`/personnel/${ownSquadId}`);
  expect(ownPageResponse?.status()).toBe(200);

  const ownApiResponse = await page.request.get(`/api/personnel/${ownSquadId}`);
  expect(ownApiResponse.status()).toBe(200);
});

test("a quartermaster never receives a whole service number", async ({
  page,
}) => {
  await signIn(page, QUARTERMASTER);

  // Weapons are the interesting category: they are the only items the seed
  // signs out to a named soldier, so this is the response that drags personnel
  // PII into a logistics endpoint.
  const response = await page.request.get(
    "/api/equipment?category=WEAPON&take=5",
  );
  expect(response.status()).toBe(200);

  const raw = await response.text();

  // Asserted against the raw body, not the parsed object, so a service number
  // leaking through some field nobody thought to check still fails. NSNs
  // (NNNN-NN-NNN-NNNN) and serial numbers (SN-NNNNNN) do not match this shape.
  expect(raw).not.toMatch(/\d{3}-\d{2}-\d{4}/);

  const body = JSON.parse(raw) as { equipment: EquipmentDTO[]; total: number };
  expect(body.equipment).toHaveLength(5);

  const assignees = body.equipment
    .map((item) => item.assignedTo)
    .filter((assignee) => assignee !== null);

  // Without this the regex above would pass on a response that simply had no
  // assignees in it, which proves nothing about masking.
  expect(assignees.length).toBeGreaterThan(0);

  for (const assignee of assignees) {
    expect(assignee.serviceId.masked).toBe(true);
    // Five bullets and the last four digits — the deliberate narrow disclosure
    // documented in lib/dto/mask.ts, not an accident of formatting.
    expect(assignee.serviceId.value).toMatch(/^•{5}\d{4}$/);
    // The name survives. Masking the assignee entirely would make the property
    // book unusable for the accountability it exists to provide.
    expect(assignee.lastName.length).toBeGreaterThan(0);
  }
});
